### ISSUE TITLE
Graph QL input

### ISSUE THREAD

**Issue by mmuller88** [mamund/alps-unified#7]
I am not very familar with Graph QL yet. But it seems the generator is missing the **input** keyword like in.

```
type demo {
  id: String!
  version: String!
}
type Query {
  getDemos: [ demo! ]
}
input DemoInput {
  version: String!
}
type Mutation {
  addDemo(input: DemoInput!): demo
}
```

I found that example here https://docs.aws.amazon.com/cdk/api/latest/docs/aws-appsync-readme.html . 
It might be a known thing :).

Cheers Martin

**Comment by mamund** [comment]
@mmuller88 :  

AFAICT, the `input` pattern in graphQL is an optimization to make it easy to share models/input-collections across multiple `Mutations`. I am not aware of any case where the `input` is a _requirement_ but do see the value of it in making SDL documents easier to read, cleaner, etc.

i'd be happy to entertain a PR that supports using `input` for SDL.

**Comment by mamund** [comment]
more in mutations and input types here:

https://graphql.org/graphql-js/mutations-and-input-types/

**Comment by mamund** [comment]
closing this for now. if anyone finds problems w/ the GraphQL / SDL output from this utility, please start a new issue w/. details.

#thanks.
